name: emploi_temps_admin
description: "A new Flutter project."
publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  http: ^0.13.5
  file_selector: ^1.0.3
  pdf: ^3.10.8
  printing: ^5.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  file_picker: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/emploi_test.json
  plugin:
    platforms:
      android:
        package: com.example.file_picker
        pluginClass: FilePickerPlugin
