// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuc1oPrWEBqg5TLu31jGTPCYYQZM6nGLA',
    appId: '1:624161995423:web:daa4a5b7484780554740aa',
    messagingSenderId: '624161995423',
    projectId: 'emploi-temps-uebolowa',
    authDomain: 'emploi-temps-uebolowa.firebaseapp.com',
    storageBucket: 'emploi-temps-uebolowa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkX7PJi6nQl0mrOxbu2cdqV7Xt_R_5Q7A',
    appId: '1:624161995423:android:8f8e81881ea35c714740aa',
    messagingSenderId: '624161995423',
    projectId: 'emploi-temps-uebolowa',
    storageBucket: 'emploi-temps-uebolowa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXB5cOD_gvhnU7NvaNZveYbmNAks3PK54',
    appId: '1:624161995423:ios:b77097f27fe32d734740aa',
    messagingSenderId: '624161995423',
    projectId: 'emploi-temps-uebolowa',
    storageBucket: 'emploi-temps-uebolowa.firebasestorage.app',
    iosBundleId: 'com.example.emploiTempsAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXB5cOD_gvhnU7NvaNZveYbmNAks3PK54',
    appId: '1:624161995423:ios:b77097f27fe32d734740aa',
    messagingSenderId: '624161995423',
    projectId: 'emploi-temps-uebolowa',
    storageBucket: 'emploi-temps-uebolowa.firebasestorage.app',
    iosBundleId: 'com.example.emploiTempsAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuc1oPrWEBqg5TLu31jGTPCYYQZM6nGLA',
    appId: '1:624161995423:web:dd721e94276a993b4740aa',
    messagingSenderId: '624161995423',
    projectId: 'emploi-temps-uebolowa',
    authDomain: 'emploi-temps-uebolowa.firebaseapp.com',
    storageBucket: 'emploi-temps-uebolowa.firebasestorage.app',
  );
}
