# Generated by Django 5.2.3 on 2025-06-30 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.classe'),
        ),
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professeur'),
        ),
        migrations.AddField(
            model_name='module',
            name='volume_horaire',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
