# Generated by Django 5.2.3 on 2025-07-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='jours',
            field=models.CharField(default='Lundi,Mardi,Mercredi,Jeudi,Vendredi,Samedi', help_text='Jours autorisés pour ce module (séparés par des virgules)', max_length=200),
        ),
    ]
