# Generated by Django 5.2.3 on 2025-07-16 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_module_heure_module_jour_module_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='api.departement'),
        ),
    ]
